"""add high_24h low_24h and ath columns

Revision ID: 9996d9100395
Revises: 
Create Date: 2026-03-31 18:09:43.638327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9996d9100395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_prices', sa.Column('high_24h', sa.Float(), nullable=True))
    op.add_column('crypto_prices', sa.Column('low_24h', sa.Float(), nullable=True))
    op.add_column('crypto_prices', sa.Column('ath_change_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_prices', 'ath_change_percentage')
    op.drop_column('crypto_prices', 'low_24h')
    op.drop_column('crypto_prices', 'high_24h')
    # ### end Alembic commands ###
